@extends('layouts.main')

@section('sidebar')
	@include("static.sidebar")
	@parent
@stop

@section('content')
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed sem scelerisque, rhoncus purus in, venenatis felis. Suspendisse facilisis pharetra diam gravida sagittis. Sed accumsan feugiat arcu, non lobortis mauris vestibulum sed. Praesent sit amet condimentum mi, ut iaculis diam. Vivamus bibendum, neque eget pulvinar efficitur, nisi turpis gravida neque, vel <a href="#">volutpat</a> massa velit quis lacus. Vestibulum et mi nibh. Integer sodales lobortis nisl id dictum. Proin sit amet erat et elit cursus pellentesque egestas at nunc. Sed eleifend turpis nisi, iaculis ultricies est placerat ac. Pellentesque odio nibh, facilisis ac <a href="#">tristique dictum</a>, varius at ipsum. Curabitur id posuere mauris. Donec vehicula libero sit amet nisi commodo, non volutpat risus molestie.</p>
	<p>Suspendisse lacinia libero eget porta pulvinar. Proin non ante libero. Aliquam ac fringilla risus. Vivamus venenatis lacus non magna volutpat, sed pellentesque urna molestie. Mauris malesuada in est at pretium. Aenean finibus libero in sapien finibus facilisis. Phasellus <a href="#">lacinia</a> eros quis justo molestie tincidunt. Donec eget congue sapien, vel dictum erat. Vivamus ullamcorper sit amet nunc eu blandit. Etiam ut egestas diam. Nulla volutpat arcu nulla, eget tristique sem suscipit id. Proin sed hendrerit massa.</p>
	<p>Ut luctus molestie mauris id finibus. Proin massa lorem, lacinia et <a href="#">ligula et</a>, consequat pellentesque urna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum mi ipsum, feugiat vestibulum mollis at, tempus quis orci. Phasellus dolor neque, volutpat sed pulvinar sed, rutrum laoreet velit. Aliquam lectus leo, facilisis eu lorem in, pulvinar feugiat massa. Morbi congue lectus ut odio consequat lobortis. Duis id arcu vel purus scelerisque tempor sit amet eu augue. Donec aliquet semper euismod. Morbi eget nibh sed nisl euismod aliquam. Suspendisse sit amet ultrices urna. Curabitur eu tempus risus.</p>
	<p>Donec eu enim vel neque ultrices aliquam. Nullam ac metus scelerisque, malesuada dolor nec, lobortis ligula. Vestibulum suscipit nisl vitae risus venenatis rhoncus. Quisque dictum molestie sodales. Mauris lorem magna, finibus ut leo ac, suscipit volutpat sapien. Sed eleifend lobortis lorem id pulvinar. Vestibulum pretium justo id lorem scelerisque, et posuere erat aliquam. Donec egestas sem ultricies gravida blandit. Etiam tellus nisi, <a href="#">dignissim</a> sed nisl mattis, maximus finibus urna. In luctus egestas euismod.</p>
	<p>Nam pulvinar risus mi, nec mollis nisi varius ac. Duis cursus mi quis leo accumsan, a dapibus eros vulputate. Sed a pharetra nibh, non ultricies sapien. Praesent molestie pellentesque dolor, at pretium purus eleifend a. Maecenas id consequat nulla. Morbi arcu nisi, sodales non felis in, varius rhoncus lorem. Sed ut efficitur nunc, vitae efficitur purus. Maecenas consectetur magna lorem, vestibulum vulputate ipsum aliquet vitae. Donec rhoncus felis ut vehicula vulputate. Pellentesque volutpat ipsum lacus, at elementum orci pharetra sed. Proin convallis auctor tortor non dictum. Nunc <a href="#">tincidunt</a> risus in magna vehicula iaculis. Ut at felis leo.</p>
@stop